### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by 10xjs** [10xjs/date-input-controller#15]
- [ ] Migrate to typescript.
- [ ] Optimize rollup build using chunks.
- [ ] UMD build
- [ ] Re-implement tests using enzyme.
- [ ] Implement state management using react hooks
- [ ] Export `useDate` hook.
